// Auto-generated - DO NOT EDIT MANUALLY
// Run scripts/split-weapons.js to regenerate
export const polearmData = [
  {
    id: "13516",
    nameEn: "Bloodsoaked Ruins",
    nameVi: "Tàn Tích Nhuốm Máu",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 674,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 22.1,
    passiveNameEn: "Mournful Tribute",
    passiveNameVi: "Tưởng Niệm Bi Thương",
    passiveDescEn:
      "For 3.5s after using an Elemental Burst, the equipping character's Lunar-Charged DMG dealt to opponents is increased by 36%. Additionally, after triggering a Lunar-Charged reaction, the equipping character will gain Requiem of Ruin: CRIT DMG is increased by 28% for 6s. They will also regain 12 Elemental Energy. Elemental Energy can be restored this way once every 14s.",
    passiveDescVi:
      'Trong 3.5s sau khi thi triển Kỹ Năng Nộ, người trang bị tăng <color=#99FFFFFF>36%</color> sát thương Nguyệt-Điện Cảm gây ra cho kẻ địch. Ngoài ra, sau khi người trang bị kích hoạt phản ứng Nguyệt-Điện Cảm, sẽ nhận được "Khúc Bi Ca Đổ Nát": Tăng <color=#99FFFFFF>28%</color> Sát Thương Bạo Kích trong 6s, đồng thời hồi phục <color=#99FFFFFF>12</color> điểm Năng Lượng Nguyên Tố cho người trang bị. Mỗi 14s tối đa hồi phục một lần Năng Lượng Nguyên Tố theo cách này.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_TummaLyhty.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13507",
    nameEn: "Calamity Queller",
    nameVi: "Hủy Diệt",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 690,
    subStat: "Tấn Công%",
    subStatValue: 16.6,
    passiveNameEn: "Extinguishing Precept",
    passiveNameVi: "Diệt Khước Giới Pháp",
    passiveDescEn:
      "Gain 12% All Elemental DMG Bonus. Obtain Consummation for 20s after using an Elemental Skill, causing ATK to increase by 3.2% per second. This ATK increase has a maximum of 6 stacks. When the character equipped with this weapon is not on the field, Consummation's ATK increase is doubled.",
    passiveDescVi:
      'Tăng <color=#99FFFFFF>12%</color> sát thương tất cả nguyên tố; Sau khi thi triển Kỹ Năng Nguyên Tố sẽ nhận được hiệu quả "Viên Đột", duy trì 20s, sức tấn công mỗi giây tăng <color=#99FFFFFF>3.2%</color>, hiệu quả tăng tấn công này tối đa cộng dồn 6 lần. Khi nhân vật trang bị vũ khí này không xuất hiện trong trận, hiệu quả tăng tấn công của "Viên Đột" tăng gấp đôi.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Santika.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13512",
    nameEn: "Crimson Moon's Semblance",
    nameVi: "Hình Thái Xích Nguyệt",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 674,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 22.1,
    passiveNameEn: "Ashen Sun's Shadow",
    passiveNameVi: "Bóng Tối Mặt Trời Tàn",
    passiveDescEn:
      "Grants a Bond of Life equal to 25% of Max HP when a Charged Attack hits an opponent. This effect can be triggered up to once every 14s. In addition, when the equipping character has a Bond of Life, they gain a 12% DMG Bonus; if the value of the Bond of Life is greater than or equal to 30% of Max HP, then gain an additional 24% DMG Bonus.",
    passiveDescVi:
      "Khi Trọng Kích trúng kẻ địch sẽ cung cấp Khế Ước Sinh Mệnh tương đương với 25% Giới Hạn HP, hiệu quả này mỗi 14s tối đa kích hoạt một lần. Ngoài ra, người trang bị khi có Khế Ước Sinh Mệnh, sát thương gây ra sẽ tăng <color=#99FFFFFF>12%</color>; Nếu giá trị Khế Ước Sinh Mệnh lớn hơn hoặc bằng 30% Giới Hạn HP, sát thương gây ra sẽ tăng thêm <color=#99FFFFFF>24%</color>.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_BloodMoon.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13517",
    nameEn: "Disaster and Remorse",
    nameVi: "Tai Họa Và Hối Hận",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 674,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 22.1,
    passiveNameEn: "Dolorous Stroke",
    passiveNameVi: "Một Đòn Tai Họa",
    passiveDescEn:
      'After the equipping character uses an Elemental Skill, they gain "Path of Conflict" for 17s, as well as "Unforgivable" and "Irreparable" for 3s each. This effect can trigger once every 18s.\\nUnforgivable: Increases the equipping character\'s Normal Attack and Charged Attack DMG by 40%.\\nIrreparable: Increases the equipping character\'s Elemental Skill and Elemental Burst DMG by 40%.\\nWhile Path of Conflict is in effect, when the equipping character hits an opponent with a Normal Attack or Charged Attack, Irreparable\'s duration will be increased by 1s. When the equipping character hits an opponent with their Elemental Skill or Elemental Burst, Unforgivable\'s duration will be increased by 1s. Each of the above effects can be triggered once every 0.1s. When Path of Conflict ends or the equipping character leaves the field, both Unforgivable and Irreparable will be removed.\\nHexerei: Secret Rite: The above DMG boosts are increased by 75%.',
    passiveDescVi:
      'Sau khi người trang bị thi triển Kỹ Năng Nguyên Tố, sẽ nhận hiệu quả "Con Đường Phân Tranh" trong 17s, đồng thời nhận hiệu quả "Không Tha Thứ" và "Không Chữa Lành" lần lượt duy trì trong 3s, mỗi 18s tối đa kích hoạt một lần.\\nKhông Tha Thứ: Sát thương Tấn Công Thường và Trọng Kích của người trang bị tăng <color=#99FFFFFF>40%</color>.\\nKhông Chữa Lành: Sát thương Kỹ Năng Nguyên Tố và Kỹ Năng Nộ của người trang bị tăng <color=#99FFFFFF>40%</color>.\\nTrong thời gian duy trì Con Đường Phân Tranh, khi Tấn Công Thường và Trọng Kích của người trang bị đánh trúng kẻ địch, Không Chữa Lành sẽ kéo dài 1s; Khi Kỹ Năng Nguyên Tố và Kỹ Năng Nộ của người trang bị đánh trúng kẻ địch, Không Tha Thứ sẽ kéo dài 1s. Hiệu quả nêu trên lần lượt mỗi 0.1s tối đa kích hoạt một lần. Khi kết thúc Con Đường Phân Tranh hoặc người trang bị rời trận, sẽ xóa Không Tha Thứ và Không Chữa Lành.\\nHexerei - Nghi Thức Bí Mật: Tất cả hiệu quả tăng sát thương kể trên sẽ tăng 75%.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Carbine.webp",
    tier: null,
    role: null,
  },
  {
    id: "13509",
    nameEn: "Engulfing Lightning",
    nameVi: "Đoạn Thảo Trường Đao",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 658,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 55.2,
    passiveNameEn: "Timeless Dream: Eternal Stove",
    passiveNameVi: "Giấc Mơ Vĩnh Cửu - Nguyên Liệu Vĩnh Hằng",
    passiveDescEn:
      "ATK increased by 28% of Energy Recharge over the base 100%. You can gain a maximum bonus of 80% ATK. Gain 30% Energy Recharge for 12s after using an Elemental Burst.",
    passiveDescVi:
      "Tăng sức tấn công nhận được, mức tăng thêm tương đương <color=#99FFFFFF>28%</color> lượng dư ra trên 100% của Hiệu Quả Nạp Nguyên Tố, tối đa tăng <color=#99FFFFFF>80%</color> từ cách này. Trong 12s sau khi thi triển Kỹ Năng Nộ, tăng <color=#99FFFFFF>30%</color> Hiệu Quả Nạp Nguyên Tố.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Narukami.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "13515",
    nameEn: "Fractured Halo",
    nameVi: "Hào Quang Tách Rời",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 658,
    subStat: "Sát Thương Bạo Kích",
    subStatValue: 66.2,
    passiveNameEn: "Purifying Crown",
    passiveNameVi: "Vương Miện Sương Trong",
    passiveDescEn:
      "After an Elemental Skill or Elemental Burst is used, ATK is increased by 24% for 20s. If the equipping character creates a Shield while this effect is active, they will gain the Electrifying Edict effect for 20s: All nearby party members deal 40% more Lunar-Charged DMG.",
    passiveDescVi:
      'Sau khi thi triển Kỹ Năng Nguyên Tố hoặc Kỹ Năng Nộ, Tấn Công tăng <color=#99FFFFFF>24%</color> trong vòng 20s. Trong thời gian duy trì, nếu người trang bị tạo ra khiên thì trong 20s tiếp theo sẽ nhận hiệu ứng "Sắc Lệnh Tia Chớp": Tăng <color=#99FFFFFF>40%</color> sát thương phản ứng Nguyệt-Điện Cảm của tất cả nhân vật trong đội ở gần.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Perdix.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13513",
    nameEn: "Lumidouce Elegy",
    nameVi: "Bi Ca Lumidouce",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 658,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 33.1,
    passiveNameEn: "Bright Dawn Overture",
    passiveNameVi: "Khúc Dạo Đầu Bình Minh",
    passiveDescEn:
      "ATK increased by 15%. After the equipping character triggers Burning on an opponent or deals Dendro DMG to Burning opponents, the DMG dealt is increased by 18%. This effect lasts for 8s, max 2 stacks. When 2 stacks are reached or when the duration is refreshed at 2 stacks, restore 12 Energy. Energy can be restored this way once every 12s. The 2 aforementioned effects can be triggered even when the character is off-field.",
    passiveDescVi:
      "Tấn Công tăng <color=#99FFFFFF>15%</color>; Người trang bị khi kích hoạt phản ứng Thiêu Đốt lên kẻ địch hoặc gây Sát Thương Nguyên Tố Thảo lên kẻ địch trong trạng thái Thiêu Đốt, sát thương gây ra sẽ tăng <color=#99FFFFFF>18%</color>. Hiệu quả này duy trì 8s, tối đa cộng dồn 2 tầng; Khi cộng dồn đến tầng 2 hoặc thời gian duy trì của tầng 2 được làm mới thì sẽ hồi phục <color=#99FFFFFF>12</color> Năng Lượng Nguyên Tố. Mỗi 12s tối đa hồi phục một lần Năng Lượng Nguyên Tố thông qua cách thức này. Nhân vật không ra trận cũng có thể kích hoạt 2 hiệu quả nêu trên.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Muguet.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13505",
    nameEn: "Primordial Jade Winged-Spear",
    nameVi: "Hòa Phác Diên",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 674,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 22.1,
    passiveNameEn: "Eagle Spear of Justice",
    passiveNameVi: "Thương Đại Bàng Ngân Nga",
    passiveDescEn:
      "On hit, increases ATK by 3.2% for 6s. Max 7 stacks. This effect can only occur once every 0.3s. While in possession of the maximum possible stacks, DMG dealt is increased by 12%.",
    passiveDescVi:
      "Khi đánh trúng kẻ địch tấn công của bản thân tăng <color=#99FFFFFF>3.2%</color>, kéo dài 6s, có thể cộng dồn 7 tầng. Mỗi 0.3s có hiệu quả 1 lần, khi cộng dồn đầy sẽ tăng <color=#99FFFFFF>12%</color> sát thương.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Morax.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "330002",
    nameEn: "Shattered Moon - Sublimation",
    nameVi: "Tàn Nguyệt - Thăng Hoa",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 400,
    subStat: null,
    subStatValue: null,
    passiveNameEn: null,
    passiveNameVi: null,
    passiveDescEn: null,
    passiveDescVi: null,
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_MorphSpinifer_Great_Wind.webp",
    tier: null,
    role: null,
  },
  {
    id: "13502",
    nameEn: "Skyward Spine",
    nameVi: "Xương Sống Thiên Không",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 674,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 36.8,
    passiveNameEn: "Black Wing",
    passiveNameVi: "Răng Nanh Đen Vỡ Nát",
    passiveDescEn:
      "Increases CRIT Rate by 8% and increases Normal ATK SPD by 12%. Additionally, Normal and Charged Attacks hits on opponents have a 50% chance to trigger a vacuum blade that deals 40% of ATK as DMG in a small AoE. This effect can occur no more than once every 2s.",
    passiveDescVi:
      "Tỷ lệ bạo kích tăng <color=#99FFFFFF>8%</color>,tốc độ tấn công thường tăng <color=#99FFFFFF>12%</color>. Ngoài ra, khi tấn công thường và trọng kích đánh trúng kẻ địch, có tỷ lệ <color=#99FFFFFF>50%</color> thi triển Lưỡi Dao Chân Không, tạo thêm sát thương bằng <color=#99FFFFFF>40%</color> tấn công trong phạm vi nhỏ. Hiệu quả này mỗi 2s thi triển nhiều nhất 1 lần.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Dvalin.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13501",
    nameEn: "Staff of Homa",
    nameVi: "Trượng Hộ Ma",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 658,
    subStat: "Sát Thương Bạo Kích",
    subStatValue: 66.2,
    passiveNameEn: "Reckless Cinnabar",
    passiveNameVi: "Bướm Đỏ Tự Do",
    passiveDescEn:
      "HP increased by 20%. Additionally, provides an ATK Bonus based on 0.8% of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK Bonus is increased by an additional 1% of Max HP.",
    passiveDescVi:
      "HP tăng <color=#99FFFFFF>20%</color>. Ngoài ra, nhận được buff tấn công bằng <color=#99FFFFFF>0.8%</color> giới hạn HP của nhân vật trang bị vũ khí này. Khi HP của nhân vật trang bị vũ khí này dưới 50%, sẽ nhận thêm buff tấn công bằng <color=#99FFFFFF>1%</color> giới hạn HP.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Homa.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "13511",
    nameEn: "Staff of the Scarlet Sands",
    nameVi: "Quyền Trượng Cát Đỏ",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 641,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 44.2,
    passiveNameEn: "Heat Haze at Horizon's End",
    passiveNameVi: "Giấc Mộng Cuối Chân Trời",
    passiveDescEn:
      "The equipping character gains 52% of their Elemental Mastery as bonus ATK. When an Elemental Skill hits opponents, the Dream of the Scarlet Sands effect will be gained for 10s: The equipping character will gain 28% of their Elemental Mastery as bonus ATK. Max 3 stacks.",
    passiveDescVi:
      'Tăng tấn công dựa trên <color=#99FFFFFF>52%</color> Tinh Thông Nguyên Tố của người trang bị vũ khí này. Khi Kỹ Năng Nguyên Tố đánh trúng kẻ địch sẽ nhận hiệu ứng "Giấc Mộng Cát Đỏ" duy trì 10s: Tăng tấn công dựa trên <color=#99FFFFFF>28%</color> Tinh Thông Nguyên Tố của người trang bị vũ khí này, hiệu quả này tối đa cộng dồn 3 tầng.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Deshret.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "13514",
    nameEn: "Symphonist of Scents",
    nameVi: "Nhạc Sĩ Hương Thơm",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 658,
    subStat: "Sát Thương Bạo Kích",
    subStatValue: 66.2,
    passiveNameEn: "Seasoned Symphony",
    passiveNameVi: "Giao Hưởng Bách Vị",
    passiveDescEn:
      'ATK is increased by 12%. When the equipping character is off-field, ATK is increased by an additional 12%. After initiating healing, the equipping character and the character(s) they have healed will obtain the "Sweet Echoes" effect, increasing their ATK by 32% for 3s. This effect can be triggered even if the equipping character is off-field.',
    passiveDescVi:
      'Tấn Công tăng <color=#99FFFFFF>12%</color>. Khi nhân vật trang bị vũ khí này không ra trận, Tấn Công tăng thêm <color=#99FFFFFF>12%</color>. Sau khi tiến hành chữa trị, người trang bị và nhân vật được chữa trị sẽ nhận hiệu ứng "Hương Thơm Nồng Nàn", Tấn Công tăng <color=#99FFFFFF>32%</color> trong 3s. Người trang bị không ra trận cũng có thể kích hoạt hiệu quả nêu trên.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Trident.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "13504",
    nameEn: "Vortex Vanquisher",
    nameVi: "Giáo Nịnh Thần",
    rarity: 5,
    type: "Vũ Khí Cán Dài",
    baseAtk: 658,
    subStat: "Tấn Công%",
    subStatValue: 49.7,
    passiveNameEn: "Golden Majesty",
    passiveNameVi: "Hoàng Cực Chương Vàng",
    passiveDescEn:
      "Increases Shield Strength by 20%. Scoring hits on opponents increases ATK by 4% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
    passiveDescVi:
      "Hiệu quả khiên tăng <color=#99FFFFFF>20%</color>. Trong vòng 8s sau khi đánh trúng, tấn công tăng <color=#99FFFFFF>4%</color>. Cộng dồn 5 tầng, mỗi 0.3s chỉ được thi triển 1 lần. Ngoài ra, khi được khiên bảo vệ, hiệu quả tăng tấn công sẽ tăng 100%.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Kunwu.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13415",
    nameEn: '"The Catch"',
    nameVi: "Lao Xiên Cá",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 46,
    passiveNameEn: "Shanty",
    passiveNameVi: "Bài Ca Của Thuyền",
    passiveDescEn:
      "Increases Elemental Burst DMG by 16% and Elemental Burst CRIT Rate by 6%.",
    passiveDescVi:
      "Sát thương Kỹ Năng Nộ gây ra tăng <color=#99FFFFFF>16%</color>, tỷ lệ bạo của Kỹ Năng Nộ tăng <color=#99FFFFFF>6%</color>.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Mori.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "13424",
    nameEn: "Ballad of the Fjords",
    nameVi: "Khúc Ca Vịnh Hẹp",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 27.6,
    passiveNameEn: "Tales of the Tundra",
    passiveNameVi: "Câu Chuyện Lãnh Nguyên",
    passiveDescEn:
      "When there are at least 3 different Elemental Types in your party, Elemental Mastery will be increased by 120.",
    passiveDescVi:
      "Khi trong đội tồn tại ít nhất 3 nhân vật không cùng loại nguyên tố, Tinh Thông Nguyên Tố tăng <color=#99FFFFFF>120</color> điểm.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Shanty.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13404",
    nameEn: "Blackcliff Pole",
    nameVi: "Thương Hắc Nham",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Sát Thương Bạo Kích",
    subStatValue: 55.2,
    passiveNameEn: "Press the Advantage",
    passiveNameVi: "Thừa Thắng Xông Lên",
    passiveDescEn:
      "After defeating an enemy, ATK is increased by 12% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    passiveDescVi:
      "Sau khi đánh bại kẻ địch, tấn công tăng <color=#99FFFFFF>12%</color>, kéo dài 30s. Hiệu quả này cộng dồn đến 3 tầng, CD mỗi tầng độc lập.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Blackrock.webp",
    tier: "B",
    role: null,
  },
  {
    id: "13403",
    nameEn: "Crescent Pike",
    nameVi: "Lưu Nguyệt Châm",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Sát Thương Vật Lý%",
    subStatValue: 34.5,
    passiveNameEn: "Infusion Needle",
    passiveNameVi: "Trâm Năng Lượng",
    passiveDescEn:
      "After picking up an Elemental Orb/Particle, Normal and Charged Attacks deal additional DMG equal to 20% of ATK for 5s.",
    passiveDescVi:
      "Trong 5s sau khi nhận Nguyên Tố Hạt Nhân hoặc Nguyên Tố Tinh Cầu, tấn công thường và trọng kích sẽ tạo thêm sát thương bằng <color=#99FFFFFF>20</color>% tấn công.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Exotic.webp",
    tier: "C",
    role: null,
  },
  {
    id: "13405",
    nameEn: "Deathmatch",
    nameVi: "Thương Quyết Chiến",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 566,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 36.8,
    passiveNameEn: "Gladiator",
    passiveNameVi: "Giác Đấu Sĩ",
    passiveDescEn:
      "If there are at least 2 opponents nearby, ATK is increased by 16% and DEF is increased by 16%. If there are fewer than 2 opponents nearby, ATK is increased by 24%.",
    passiveDescVi:
      "Khi bên cạnh có ít nhất 2 kẻ địch, được tăng <color=#99FFFFFF>16%</color> tấn công và <color=#99FFFFFF>16%</color> phòng ngự, khi có dưới 2 kẻ địch, được tăng <color=#99FFFFFF>24%</color> tấn công.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Gladiator.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13426",
    nameEn: "Dialogues of the Desert Sages",
    nameVi: "Đối Thoại Của Hiền Giả Sa Mạc",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "HP%",
    subStatValue: 41.4,
    passiveNameEn: "Principle of Equilibrium",
    passiveNameVi: "Nguyên Lý Cân Bằng",
    passiveDescEn:
      "When the wielder performs healing, restore 8 Energy. This effect can be triggered once every 10s and can occur even when the character is not on the field.",
    passiveDescVi:
      "Khi tiến hành trị liệu, hồi phục <color=#99FFFFFF>8</color> điểm năng lượng. Hiệu quả này mỗi 10s tối đa kích hoạt một lần, nhân vật không ra trận cũng có thể kích hoạt.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Caduceus.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13401",
    nameEn: "Dragon's Bane",
    nameVi: "Tai Ương Của Rồng",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 566,
    subStat: "Tinh Thông Nguyên Tố",
    subStatValue: 250,
    passiveNameEn: "Bane of Flame and Water",
    passiveNameVi: "Diệt Hỏa Ngưng Thủy",
    passiveDescEn:
      "Increases DMG against opponents affected by Hydro or Pyro by 20%.",
    passiveDescVi:
      "Sát thương tạo ra cho kẻ địch bị ảnh hưởng bởi Nguyên Tố Thủy hoặc Hỏa tăng <color=#99FFFFFF>20%</color>.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Stardust.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13409",
    nameEn: "Dragonspine Spear",
    nameVi: "Thương Long Tích",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 566,
    subStat: "Sát Thương Vật Lý%",
    subStatValue: 69.1,
    passiveNameEn: "Frost Burial",
    passiveNameVi: "Sương Táng",
    passiveDescEn:
      "Hitting an opponent with Normal and Charged Attacks has a 60% chance of forming and dropping an Everfrost Icicle above them, dealing AoE DMG equal to 80% of ATK. Opponents affected by Cryo are instead dealt DMG equal to 200% of ATK. Can only occur once every 10s.",
    passiveDescVi:
      "Khi tấn công thường và trọng kích đánh trúng kẻ địch có tỷ lệ <color=#99FFFFFF>60%</color> tạo ra Đá Vĩnh Hằng phía trên kẻ địch và rơi xuống, gây sát thương phạm vi bằng <color=#99FFFFFF>80%</color> tấn công. Nếu địch bị ảnh hưởng bởi nguyên tố Băng, sẽ gây sát thương bằng <color=#99FFFFFF>200%</color> tấn công. Hiệu quả này mỗi 10s kích hoạt 1 lần.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Everfrost.webp",
    tier: "C",
    role: null,
  },
  {
    id: "13407",
    nameEn: "Favonius Lance",
    nameVi: "Thương Tây Phong",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 30.7,
    passiveNameEn: "Windfall",
    passiveNameVi: "Đi Cùng Với Gió",
    passiveDescEn:
      "CRIT Hits have a 60% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12s.",
    passiveDescVi:
      "Khi tạo thành bạo kích có tỷ lệ <color=#99FFFFFF>60%</color> sinh ra một lượng nhỏ Nguyên Tố Hạt Nhân, khôi phục 6 Năng Lượng Nguyên Tố cho nhân vật. Mỗi <color=#99FFFFFF>12</color>s mới thi triển 1 lần.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Zephyrus.webp",
    tier: "SS",
    role: null,
  },
  {
    id: "13431",
    nameEn: "Footprint of the Rainbow",
    nameVi: "Vết Tích Cầu Vồng",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Phòng Ngự%",
    subStatValue: 51.8,
    passiveNameEn: "Pact of Flowing Springs",
    passiveNameVi: "Giao Ước Giữa Sông Và Suối",
    passiveDescEn: "Using an Elemental Skill increases DEF by 16% for 15s.",
    passiveDescVi:
      "Khi thi triển Kỹ Năng Nguyên Tố, phòng ngự tăng <color=#99FFFFFF>16%</color> trong 15s.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Isikhulu.webp",
    tier: "C",
    role: null,
  },
  {
    id: "13414",
    nameEn: "Kitain Cross Spear",
    nameVi: "Giáo Thập Tự Kitain",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Tinh Thông Nguyên Tố",
    subStatValue: 125,
    passiveNameEn: "Samurai Conduct",
    passiveNameVi: "Vũ Điệu Samurai",
    passiveDescEn:
      "Increases Elemental Skill DMG by 6%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
    passiveDescVi:
      "Tăng sát thương Kỹ Năng Nguyên Tố <color=#99FFFFFF>6%</color>. Sau khi Kỹ Năng Nguyên Tố đánh trúng, nhân vật mất 3 điểm Năng Lượng Nguyên Tố, đồng thời 6 giây tiếp theo mỗi 2 giây hồi phục <color=#99FFFFFF>3</color> điểm. Hiệu quả này mỗi 10 giây kích hoạt 1 lần, nhân vật ở trong đội nhưng không ra trận vẫn có thể kích hoạt.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Bakufu.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13406",
    nameEn: "Lithic Spear",
    nameVi: "Thương Thiên Nham",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Tấn Công%",
    subStatValue: 27.6,
    passiveNameEn: "Lithic Axiom: Unity",
    passiveNameVi: "Thiên Nham Quyết - Đồng Tâm",
    passiveDescEn:
      "For every character in the party who hails from Liyue, the character who equips this weapon gains a 7% ATK increase and a 3% CRIT Rate increase. This effect stacks up to 4 times.",
    passiveDescVi:
      "Mỗi khi trong đội có 1 nhân vật Liyue, nhân vật trang bị vũ khí này sẽ nhận <color=#99FFFFFF>7%</color> tăng tấn công và <color=#99FFFFFF>3%</color> tăng tỷ lệ bạo kích. Nhiều nhất có thể nhận 4 tầng hiệu quả tăng.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Lapis.webp",
    tier: "B",
    role: null,
  },
  {
    id: "13419",
    nameEn: "Missive Windspear",
    nameVi: "Mũi Nhọn Của Gió",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Tấn Công%",
    subStatValue: 41.4,
    passiveNameEn: "The Wind Unattained",
    passiveNameVi: "Ngọn Gió Không Đến",
    passiveDescEn:
      "Within 10s after an Elemental Reaction is triggered, ATK is increased by 12% and Elemental Mastery is increased by 48.",
    passiveDescVi:
      "Trong 10s sau khi kích hoạt phản ứng nguyên tố, tấn công tăng <color=#99FFFFFF>12%</color>, Tinh Thông Nguyên Tố tăng <color=#99FFFFFF>48</color> điểm.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Windvane.webp",
    tier: "B",
    role: null,
  },
  {
    id: "13417",
    nameEn: "Moonpiercer",
    nameVi: "Quán Nguyệt Thương",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Tinh Thông Nguyên Tố",
    subStatValue: 125,
    passiveNameEn: "Stillwood Moonshadow",
    passiveNameVi: "Ánh Trăng Rừng Tối",
    passiveDescEn:
      "After triggering Burning, Quicken, Aggravate, Spread, Bloom, Lunar-Bloom, Hyperbloom, or Burgeon, a Leaf of Revival will be created around the character for a maximum of 10s. When picked up, the Leaf will grant the character 16% ATK for 12s. Only 1 Leaf can be generated this way every 20s. This effect can still be triggered if the character is not on the field.",
    passiveDescVi:
      'Sau khi kích hoạt phản ứng Thiêu Đốt, Sinh Trưởng, Tăng Cường, Lan Tràn, Sum Suê, Nguyệt-Sum Suê, Nở Rộ hoặc Bung Tỏa sẽ sản sinh "Lá Phục Sinh" tồn tại tối đa 10s ở xung quanh nhân vật. Nhân vật khi nhặt "Lá Phục Sinh" sẽ tăng <color=#99FFFFFF>16%</color> tấn công, duy trì 12s. Mỗi 20s tối đa sản sinh một "Lá Phục Sinh" bằng cách này. Nhân vật khi không ra trận cũng sẽ kích hoạt.',
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Arakalari.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13430",
    nameEn: "Mountain-Bracing Bolt",
    nameVi: "Mũi Đinh Trấn Núi",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 30.7,
    passiveNameEn: "Hope Beyond the Peaks",
    passiveNameVi: "Hy Vọng Vượt Qua Đỉnh Núi",
    passiveDescEn:
      "Decreases Climbing Stamina Consumption by 15% and increases Elemental Skill DMG by 12%. Also, after other nearby party members use Elemental Skills, the equipping character's Elemental Skill DMG will also increase by 12% for 8s.",
    passiveDescVi:
      "Giảm 15% tiêu hao thể lực khi leo trèo, tăng <color=#99FFFFFF>12%</color> sát thương Kỹ Năng Nguyên Tố gây ra; Ngoài ra, sau khi nhân vật khác trong đội gần đó thi triển Kỹ Năng Nguyên Tố, sát thương Kỹ Năng Nguyên Tố của người trang bị sẽ còn tăng <color=#99FFFFFF>12%</color> trong 8s.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Umpakati.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13427",
    nameEn: "Prospector's Drill",
    nameVi: "Mũi Khoan Thăm Dò",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Tấn Công%",
    subStatValue: 27.6,
    passiveNameEn: "Masons' Ditty",
    passiveNameVi: "Khúc Ca Thợ Đẽo Đá",
    passiveDescEn:
      "When the wielder is healed or heals others, they will gain a Unity's Symbol that lasts 30s, up to a maximum of 3 Symbols. When using their Elemental Skill or Burst, all Symbols will be consumed and the Struggle effect will be granted for 10s. For each Symbol consumed, gain 3% ATK and 7% All Elemental DMG Bonus. The Struggle effect can be triggered once every 15s, and Symbols can be gained even when the character is not on the field.",
    passiveDescVi:
      "Khi trị liệu hoặc nhận trị liệu sẽ nhận một Ký Hiệu Đoàn Kết, duy trì 30s, tối đa có được 3 Ký Hiệu. Khi thi triển Kỹ Năng Nguyên Tố hoặc Kỹ Năng Nộ sẽ tiêu hao tất cả Ký Hiệu để sản sinh hiệu quả Chống Đối trong 10s：Mỗi Ký Hiệu tiêu hao sẽ tăng <color=#99FFFFFF>3%</color> tấn công và <color=#99FFFFFF>7%</color> buff sát thương tất cả nguyên tố. Mỗi 15s tối đa kích hoạt một lần hiệu quả Chống Đối; Nhân vật không ra trận cũng có thể nhận được Ký Hiệu Đoàn Kết.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Mechanic.webp",
    tier: "A",
    role: null,
  },
  {
    id: "13433",
    nameEn: "Prospector's Shovel",
    nameVi: "Xẻng Đào Vàng",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Tấn Công%",
    subStatValue: 41.4,
    passiveNameEn: "Swift and Sure",
    passiveNameVi: "Thời Cơ Quyết Đoán",
    passiveDescEn:
      "Electro-Charged DMG is increased by 48%, and Lunar-Charged DMG is increased by 12%. Moonsign: Ascendant Gleam: Lunar-Charged DMG is increased by an additional 12%.",
    passiveDescVi:
      "Sát thương phản ứng Điện Cảm tăng <color=#99FFFFFF>48%</color>, sát thương phản ứng Nguyệt-Điện Cảm tăng <color=#99FFFFFF>12%</color>. Nguyệt Triệu - Rực Sáng: Sát thương phản ứng Nguyệt-Điện Cảm tăng thêm <color=#99FFFFFF>12%</color>.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Ilmarinen.webp",
    tier: null,
    role: null,
  },
  {
    id: "13402",
    nameEn: "Prototype Starglitter",
    nameVi: "Mẫu Tinh Liêm",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 579,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 46,
    passiveNameEn: "Magic Affinity",
    passiveNameVi: "Thị Ma",
    passiveDescEn:
      "After using an Elemental Skill, increases Normal and Charged Attack DMG by 8% for 12s. Max 2 stacks.",
    passiveDescVi:
      "Sau khi thi triển kỹ năng nguyên tố, sát thương tấn công thường và trọng kích tăng <color=#99FFFFFF>8%</color>. Kéo dài 12s, tối đa cộng dồn 2 tầng.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Proto.webp",
    tier: "C",
    role: null,
  },
  {
    id: "13425",
    nameEn: "Rightful Reward",
    nameVi: "Thù Lao Của Chính Nghĩa",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "HP%",
    subStatValue: 27.6,
    passiveNameEn: "Tip of the Spear",
    passiveNameVi: "Mũi Nhọn Của Thương",
    passiveDescEn:
      "When the wielder is healed, restore 8 Energy. This effect can be triggered once every 10s, and can occur even when the character is not on the field.",
    passiveDescVi:
      "Khi nhận trị liệu, hồi phục <color=#99FFFFFF>8</color> điểm năng lượng. Hiệu quả này mỗi 10s tối đa kích hoạt một lần, nhân vật không ra trận cũng có thể kích hoạt.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Vorpal.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13408",
    nameEn: "Royal Spear",
    nameVi: "Thương Săn Tông Thất",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Tấn Công%",
    subStatValue: 27.6,
    passiveNameEn: "Focus",
    passiveNameVi: "Chuyên Chú",
    passiveDescEn:
      "Upon damaging an opponent, increases CRIT Rate by 8%. Max 5 stacks. A CRIT Hit removes all stacks.",
    passiveDescVi:
      "Khi tấn công tạo thành sát thương, tăng tỷ lệ bạo kích <color=#99FFFFFF>8%</color>, nhiều nhất cộng dồn 5 lần. Sau khi tấn công tạo thành bạo kích, xóa hiệu quả Chuyên Chú đã có.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Theocrat.webp",
    tier: null,
    role: null,
  },
  {
    id: "13434",
    nameEn: "Sacrificer's Staff",
    nameVi: "Quyền Trượng Kẻ Thánh Tế",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 606,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 9.2,
    passiveNameEn: "Untainted Desire",
    passiveNameVi: "Mong Muốn Chưa Vấy Bẩn",
    passiveDescEn:
      "For 6s after an Elemental Skill hits an opponent, ATK is increased by 8% and Energy Recharge is increased by 6%. Max 3 stacks. This effect can be triggered even when the equipping character is off-field.",
    passiveDescVi:
      "Trong 6s sau khi Kỹ Năng Nguyên Tố đánh trúng kẻ địch, Tấn Công tăng <color=#99FFFFFF>8%</color>, Hiệu Quả Nạp Nguyên Tố tăng <color=#99FFFFFF>6%</color>. Hiệu quả này tối đa cộng dồn 3 tầng, người trang bị khi không ra trận vẫn có thể kích hoạt.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Krivule.webp",
    tier: "A",
    role: null,
  },
  {
    id: "330001",
    nameEn: "Shattered Moon",
    nameVi: "Tàn Nguyệt",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 400,
    subStat: null,
    subStatValue: null,
    passiveNameEn: null,
    passiveNameVi: null,
    passiveDescEn: null,
    passiveDescVi: null,
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_MorphSpinifer_Wind.webp",
    tier: null,
    role: null,
  },
  {
    id: "13432",
    nameEn: "Tamayuratei no Ohanashi",
    nameVi: "Tamayuratei no Ohanashi",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 592,
    subStat: "Hiệu Quả Nạp",
    subStatValue: 30.7,
    passiveNameEn: "Busybody's Running Light",
    passiveNameVi: "Ngọn Đèn Tinh Nghịch",
    passiveDescEn:
      "Increase ATK by 20% and Movement SPD by 10% for 10s when using an Elemental Skill.",
    passiveDescVi:
      "Khi thi triển Kỹ Năng Nguyên Tố, tăng <color=#99FFFFFF>20%</color> Tấn Công và 10% Tốc Độ Di Chuyển trong 10s.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Aoandon.webp",
    tier: "B",
    role: null,
  },
  {
    id: "13416",
    nameEn: "Wavebreaker's Fin",
    nameVi: "Vây Cá Chẻ Sóng",
    rarity: 4,
    type: "Vũ Khí Cán Dài",
    baseAtk: 606,
    subStat: "Tấn Công%",
    subStatValue: 13.8,
    passiveNameEn: "Watatsumi Wavewalker",
    passiveNameVi: "Kẻ Cưỡi Sóng Watatsumi",
    passiveDescEn:
      "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12%. A maximum of 40% increased Elemental Burst DMG can be achieved this way.",
    passiveDescVi:
      "Tổng giới hạn Năng Lượng Nguyên Tố của tất cả nhân vật trong đội, mỗi 1 điểm sẽ tăng <color=#99FFFFFF>0.12%</color> sát thương Kỹ Năng Nộ của nhân vật trang bị vũ khí này gây ra. Thông qua cách này, sát thương Kỹ Năng Nộ tăng tối đa <color=#99FFFFFF>40%</color>.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Maria.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13303",
    nameEn: "Black Tassel",
    nameVi: "Hắc Anh Thương",
    rarity: 3,
    type: "Vũ Khí Cán Dài",
    baseAtk: 393,
    subStat: "HP%",
    subStatValue: 61.3,
    passiveNameEn: "Bane of the Soft",
    passiveNameVi: "Khắc Nhu",
    passiveDescEn: "Increases DMG against slimes by 40%.",
    passiveDescVi:
      "Tăng <color=#99FFFFFF>40%</color> sát thương với kẻ địch là Slime.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Noire.webp",
    tier: "S",
    role: null,
  },
  {
    id: "13302",
    nameEn: "Halberd",
    nameVi: "Thuẫn Kích",
    rarity: 3,
    type: "Vũ Khí Cán Dài",
    baseAtk: 410,
    subStat: "Tấn Công%",
    subStatValue: 30.6,
    passiveNameEn: "Heavy",
    passiveNameVi: "Trầm Trọng",
    passiveDescEn:
      "Normal Attacks deal an additional 160% ATK as DMG. Can only occur once every 10s.",
    passiveDescVi:
      "Gây thêm sát thương bằng <color=#99FFFFFF>160%</color> Tấn Công cho kẻ địch bị Tấn Công Thường đánh trúng. Mỗi 10s tối đa kích hoạt một lần.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Halberd.webp",
    tier: null,
    role: null,
  },
  {
    id: "13301",
    nameEn: "White Tassel",
    nameVi: "Thương Bạch Anh",
    rarity: 3,
    type: "Vũ Khí Cán Dài",
    baseAtk: 401,
    subStat: "Tỷ Lệ Bạo Kích",
    subStatValue: 30.6,
    passiveNameEn: "Sharp",
    passiveNameVi: "Sắc Bén",
    passiveDescEn: "Increases Normal Attack DMG by 24%.",
    passiveDescVi:
      "Tấn công thường sát thương tăng <color=#99FFFFFF>24%</color>.",
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Ruby.webp",
    tier: "B",
    role: null,
  },
  {
    id: "13201",
    nameEn: "Iron Point",
    nameVi: "Thương Sắt",
    rarity: 2,
    type: "Vũ Khí Cán Dài",
    baseAtk: 289,
    subStat: null,
    subStatValue: null,
    passiveNameEn: null,
    passiveNameVi: null,
    passiveDescEn: null,
    passiveDescVi: null,
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Rod.webp",
    tier: null,
    role: null,
  },
  {
    id: "13101",
    nameEn: "Beginner's Protector",
    nameVi: "Thương Tân Thủ",
    rarity: 1,
    type: "Vũ Khí Cán Dài",
    baseAtk: 217,
    subStat: null,
    subStatValue: null,
    passiveNameEn: null,
    passiveNameVi: null,
    passiveDescEn: null,
    passiveDescVi: null,
    iconUrl: "/assets/weapons/UI_EquipIcon_Pole_Gewalt.webp",
    tier: null,
    role: null,
  },
];
