export const sandrone = {
  characterId: "sandrone",
  tier: "S",
  role: "Main DPS",
  recommendedC: "C0",
  tierNoteEn: [],
  tierNoteVi: [],
  stats: [],
  ascensionMats: [],
  talentMats: [],
  talentPriority: ["Elemental Burst", "Elemental Skill", "Normal Attack"],
  signatureWeapons: [],
  teams: [],
  sands: ["ATK%"],
  goblet: ["Elemental DMG Bonus"],
  circlet: ["CRIT Rate"],
  subStatsPriority: ["CRIT Rate", "CRIT DMG", "ATK%"],
  bestWeapons: [],
  bestArtifacts: []
};
