import fs from 'fs';
import path from 'path';
import { prisma } from './prisma';

export async function exportDatabaseToSeeds() {
  console.log("Exporting database to TS files...");

  // ===== Export Weapons =====
  try {
    const weapons = await prisma.weapon.findMany({ orderBy: [{ rarity: 'desc' }, { nameEn: 'asc' }] });
    const weaponsDir = path.join(__dirname, '../prisma/seeds');
    const weaponEntries = weapons.map(w => {
      return `  ${JSON.stringify(w)}`;
    });
    const weaponsFileContent = `// Auto-generated by exportDatabaseToSeeds - DO NOT EDIT MANUALLY
export const weaponsData = [
${weaponEntries.join(',\n')}
];
`;
    fs.writeFileSync(path.join(weaponsDir, 'weapons-data.ts'), weaponsFileContent, 'utf-8');
    console.log(`Exported ${weapons.length} weapons to weapons-data.ts`);
  } catch (e: any) {
    console.error('Error exporting weapons:', e.message);
  }

  // ===== Export Artifacts =====
  try {
    const artifacts = await prisma.artifactSet.findMany({ orderBy: [{ id: 'asc' }] });
    const artifactsDir = path.join(__dirname, '../prisma/seeds');
    const artifactEntries = artifacts.map(a => {
      return `  ${JSON.stringify(a)}`;
    });
    const artifactsFileContent = `// Auto-generated by exportDatabaseToSeeds - DO NOT EDIT MANUALLY
export const artifactsData = [
${artifactEntries.join(',\n')}
];
`;
    fs.writeFileSync(path.join(artifactsDir, 'artifacts-data.ts'), artifactsFileContent, 'utf-8');
    console.log(`Exported ${artifacts.length} artifact sets to artifacts-data.ts`);
  } catch (e: any) {
    console.error('Error exporting artifacts:', e.message);
  }

  // ===== Export Characters =====
  
  const characters = await prisma.character.findMany({
    include: {
      bestWeapons: { orderBy: [{ rank: 'asc' }, { id: 'asc' }] },
      bestArtifacts: { orderBy: [{ order: 'asc' }, { id: 'asc' }] },
      teams: {
        include: { members: { orderBy: { id: 'asc' } } },
        orderBy: [{ order: 'asc' }, { id: 'asc' }]
      }
    }
  });

  const charDir = path.join(__dirname, '../prisma/seeds/characters');
  if (!fs.existsSync(charDir)) {
    fs.mkdirSync(charDir, { recursive: true });
  }

  const exportNames: string[] = [];

  for (const char of characters) {
    const camelCaseName = char.id.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
    exportNames.push(camelCaseName);

    const fileContent = `export const ${camelCaseName} = {
  characterId: ${JSON.stringify(char.id)},
  tier: ${JSON.stringify(char.tier)},
  role: ${JSON.stringify(char.role)},
  recommendedC: ${JSON.stringify(char.recommendedC)},
  tierNoteEn: ${JSON.stringify(char.tierNoteEn)},
  tierNoteVi: ${JSON.stringify(char.tierNoteVi)},
  stats: ${JSON.stringify(char.stats, null, 2)},
  ascensionMats: ${JSON.stringify(char.ascensionMats, null, 2)},
  talentMats: ${JSON.stringify(char.talentMats, null, 2)},
  talentPriority: ${JSON.stringify(char.talentPriority, null, 2)},
  signatureWeapons: ${JSON.stringify(char.signatureWeapons, null, 2)},
  teams: ${JSON.stringify(char.teams.map(t => ({
    name: t.name,
    rank: t.rank,
    description: t.description,
    members: t.members.map(m => ({
      characterId: m.characterId,
      role: m.role,
      roleDesc: m.roleDesc,
      weapons: m.weapons,
      artifacts: m.artifacts,
      substats: m.substats
    }))
  })), null, 4).replace(/"([^"]+)":/g, '$1:')},
  bestWeapons: ${JSON.stringify(char.bestWeapons.map(w => ({
    rank: w.rank,
    nameVi: w.nameVi,
    nameEn: w.nameEn,
    subStat: w.subStat,
    isF2P: w.isF2P,
    refinement: w.refinement ? 'R' + w.refinement : null,
    passiveDescVi: w.passiveDescVi,
    passiveDescEn: w.passiveDescEn,
    iconUrl: w.iconUrl
  })), null, 4).replace(/"([^"]+)":/g, '$1:')},
  bestArtifacts: ${JSON.stringify(char.bestArtifacts.map(a => ({
    setNameVi: a.setNameVi,
    setNameEn: a.setNameEn,
    pieces: a.pieces,
    sands: a.sands,
    goblet: a.goblet,
    circlet: a.circlet,
    subStatsPriority: a.subStatsPriority
  })), null, 4).replace(/"([^"]+)":/g, '$1:')}
};
`;
    fs.writeFileSync(path.join(charDir, `${char.id}.ts`), fileContent, 'utf-8');
  }

  // Rewrite the index characters.ts file (just the imports and metaBuilds array part)
  const indexFile = path.join(__dirname, '../prisma/seeds/characters.ts');
  let content = fs.existsSync(indexFile) ? fs.readFileSync(indexFile, 'utf-8') : '';
  
  // Replace the imports and metaBuilds array
  const importsStr = characters.map(c => {
    const camelCaseName = c.id.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
    return `import { ${camelCaseName} } from './characters/${c.id}';`;
  }).join('\n');
  
  const arrayStr = `const metaBuilds = [\n  ${exportNames.join(',\n  ')}\n];`;

  // We find the place to replace. This is a bit tricky with Regex.
  const modifiedContent = content
    .replace(/import\s+\{[^}]+\}\s+from\s+['"]\.\/characters\/[^'"]+['"];\r?\n?/g, '')
    .replace(/const metaBuilds = \[[\s\S]*?\];/, `${importsStr}\n\n${arrayStr}`);

  // In case the replace failed (no match), append
  if (modifiedContent.includes('const metaBuilds = [')) {
    fs.writeFileSync(indexFile, modifiedContent, 'utf-8');
  } else {
     // fallback
     console.log("Could not find metaBuilds array to replace. Skipping characters.ts update.");
  }

  return true;
}
