// Auto-generated - DO NOT EDIT MANUALLY
// Run scripts/split-artifacts.js to regenerate
export const earlyData = [
  {"id":"10001","nameEn":"Resolution of Sojourner","nameVi":"Trái Tim Hành Giả","rarityList":[3,4],"piece2DescEn":"ATK +18%.","piece2DescVi":"Tấn công tăng 18%","piece4DescEn":"Increases Charged Attack CRIT Rate by 30%.","piece4DescVi":"Tỷ lệ bạo kích của trọng kích tăng 30%","iconUrl":"/assets/artifacts/UI_RelicIcon_10001_4.webp"},
  {"id":"10002","nameEn":"Brave Heart","nameVi":"Trái Tim Dũng Sĩ","rarityList":[3,4],"piece2DescEn":"ATK +18%.","piece2DescVi":"Tấn công tăng 18%","piece4DescEn":"Increases DMG by 30% against opponents with more than 50% HP.","piece4DescVi":"Kẻ địch có HP cao hơn 50%, sát thương gây ra tăng 30%.","iconUrl":"/assets/artifacts/UI_RelicIcon_10002_4.webp"},
  {"id":"10003","nameEn":"Defender's Will","nameVi":"Trái Tim Thủ Hộ","rarityList":[3,4],"piece2DescEn":"DEF +30%","piece2DescVi":"Phòng ngự tăng 30%.","piece4DescEn":"For each different element present in your own party, the wearer's Elemental RES to that corresponding element is increased by 30%.","piece4DescVi":"Cứ mỗi nhân vật của bản thân có 1 nguyên tố khác trong đội thì bản thân sẽ được nhận 30% kháng Nguyên Tố tương ứng.","iconUrl":"/assets/artifacts/UI_RelicIcon_10003_4.webp"},
  {"id":"10004","nameEn":"Tiny Miracle","nameVi":"Kỳ Tích","rarityList":[3,4],"piece2DescEn":"All Elemental RES increased by 20%.","piece2DescVi":"Tất cả kháng Nguyên Tố tăng 20%.","piece4DescEn":"Incoming elemental DMG increases corresponding Elemental RES by 30% for 10s. Can only occur once every 10s.","piece4DescVi":"Sau khi nhận sát thương Nguyên Tố, kháng tương ứng tăng 30%, kéo dài 10s. Mỗi 10s chỉ thi triển 1 lần.","iconUrl":"/assets/artifacts/UI_RelicIcon_10004_4.webp"},
  {"id":"10005","nameEn":"Berserker","nameVi":"Cuồng Chiến","rarityList":[3,4],"piece2DescEn":"CRIT Rate +12%","piece2DescVi":"Tỷ lệ bạo kích tăng 12%.","piece4DescEn":"When HP is below 70%, CRIT Rate increases by an additional 24%.","piece4DescVi":"Khi HP dưới 70%, tỷ lệ bạo kích tăng thêm 24%.","iconUrl":"/assets/artifacts/UI_RelicIcon_10005_4.webp"},
  {"id":"10006","nameEn":"Martial Artist","nameVi":"Võ Nhân","rarityList":[3,4],"piece2DescEn":"Normal and Charged Attack DMG +15%","piece2DescVi":"Tăng 15% sát thương tấn công thường và trọng kích.","piece4DescEn":"After using Elemental Skill, increases Normal Attack and Charged Attack DMG by 25% for 8s.","piece4DescVi":"Trong 8s sau khi sử dụng kỹ năng Nguyên Tố, tấn công thường và trọng kích tăng 25% sát thương.","iconUrl":"/assets/artifacts/UI_RelicIcon_10006_4.webp"},
  {"id":"10007","nameEn":"Instructor","nameVi":"Giáo Quan","rarityList":[3,4],"piece2DescEn":"Increases Elemental Mastery by 80.","piece2DescVi":"Tăng 80 điểm tinh thông nguyên tố.","piece4DescEn":"Upon triggering an Elemental Reaction, increases all party members' Elemental Mastery by 120 for 8s.","piece4DescVi":"Sau khi kích hoạt phản ứng Nguyên Tố, tinh thông Nguyên Tố tất cả thành viên đội tăng 120 điểm, kéo dài 8s.","iconUrl":"/assets/artifacts/UI_RelicIcon_10007_4.webp"},
  {"id":"10008","nameEn":"Gambler","nameVi":"Con Bạc","rarityList":[3,4],"piece2DescEn":"Increases Elemental Skill DMG by 20%.","piece2DescVi":"Sát thương kỹ năng Nguyên Tố tạo thành tăng 20%.","piece4DescEn":"Defeating an opponent has a 100% chance to remove Elemental Skill CD. Can only occur once every 15s.","piece4DescVi":"Khi đánh bại kẻ địch, có tỷ lệ 100% xóa CD kỹ năng Nguyên Tố. Mỗi 15s mới có hiệu quả 1 lần.","iconUrl":"/assets/artifacts/UI_RelicIcon_10008_4.webp"},
  {"id":"10009","nameEn":"The Exile","nameVi":"Kẻ Lưu Đày","rarityList":[3,4],"piece2DescEn":"Energy Recharge +20%","piece2DescVi":"Hiệu Quả Nạp Nguyên Tố tăng 20%","piece4DescEn":"Using an Elemental Burst regenerates 2 Energy for all party members (excluding the wearer) every 2s for 6s. This effect cannot stack.","piece4DescVi":"Sau khi thi triển kỹ năng nộ, mỗi 2 giây sẽ hồi 2 điểm năng lượng nguyên tố cho tất cả nhân vật trong đội (không bao gồm bản thân). Hiệu quả trong 6 giây, không cộng dồn.","iconUrl":"/assets/artifacts/UI_RelicIcon_10009_4.webp"},
  {"id":"10010","nameEn":"Adventurer","nameVi":"Nhà Mạo Hiểm","rarityList":[1,2,3],"piece2DescEn":"Max HP increased by 1,000.","piece2DescVi":"HP tối đa tăng 1000 điểm.","piece4DescEn":"Opening a chest regenerates 30% Max HP over 5s.","piece4DescVi":"5s sau khi mở các loại rương, duy trì hồi 30% HP.","iconUrl":"/assets/artifacts/UI_RelicIcon_10010_4.webp"},
  {"id":"10011","nameEn":"Lucky Dog","nameVi":"Vật May Mắn","rarityList":[1,2,3],"piece2DescEn":"DEF increased by 100.","piece2DescVi":"Phòng ngự tăng 100 điểm.","piece4DescEn":"Picking up Mora restores 300 HP.","piece4DescVi":"Khi nhặt Mora, hồi 300 điểm HP.","iconUrl":"/assets/artifacts/UI_RelicIcon_10011_4.webp"},
  {"id":"10012","nameEn":"Scholar","nameVi":"Học Sĩ","rarityList":[3,4],"piece2DescEn":"Energy Recharge +20%","piece2DescVi":"Hiệu Quả Nạp Nguyên Tố tăng 20%","piece4DescEn":"Gaining Elemental Particles or Orbs gives 3 Energy to all party members who have a bow or a catalyst equipped. Can only occur once every 3s.","piece4DescVi":"Khi nhận Nguyên Tố Hạt Nhân hoặc Nguyên Tố Tinh Cầu, tất cả nhân vật dùng cung tên và Pháp Khí trong đội sẽ hồi thêm 3 Năng Lượng Nguyên Tố. Mỗi 3s mới thi triển 1 lần.","iconUrl":"/assets/artifacts/UI_RelicIcon_10012_4.webp"},
  {"id":"10013","nameEn":"Traveling Doctor","nameVi":"Thầy Thuốc","rarityList":[1,2,3],"piece2DescEn":"Increases incoming healing by 20%.","piece2DescVi":"Tăng 20% hiệu quả trị liệu nhân vật nhận được.","piece4DescEn":"Using Elemental Burst restores 20% HP.","piece4DescVi":"Khi thi triển Kỹ Năng Nộ, hồi 20% HP.","iconUrl":"/assets/artifacts/UI_RelicIcon_10013_4.webp"},
  {"id":"14001","nameEn":"Blizzard Strayer","nameVi":"Dũng Sĩ Trong Băng Giá","rarityList":[4,5],"piece2DescEn":"Cryo DMG Bonus +15%","piece2DescVi":"Tăng sát thương nguyên tố Băng 15%","piece4DescEn":"When a character attacks an opponent affected by Cryo, their CRIT Rate is increased by 20%. If the opponent is Frozen, CRIT Rate is increased by an additional 20%.","piece4DescVi":"Khi tấn công kẻ địch đang bị Nguyên Tố Băng ảnh hưởng, sẽ tăng 20% tỷ lệ bạo kích, nếu địch ở trạng thái đóng băng, sẽ tăng thêm 20% tỷ lệ bạo kích.","iconUrl":"/assets/artifacts/UI_RelicIcon_14001_4.webp"},
  {"id":"14002","nameEn":"Thundersoother","nameVi":"Tôn Giả Trầm Lặng","rarityList":[4,5],"piece2DescEn":"Electro RES increased by 40%.","piece2DescVi":"Kháng nguyên tố Lôi tăng 40%.","piece4DescEn":"Increases DMG against opponents affected by Electro by 35%.","piece4DescVi":"Tăng 35% sát thương tạo thành cho kẻ địch bị ảnh hưởng nguyên tố Lôi.","iconUrl":"/assets/artifacts/UI_RelicIcon_14002_4.webp"},
  {"id":"14003","nameEn":"Lavawalker","nameVi":"Hiền Nhân Bốc Lửa","rarityList":[4,5],"piece2DescEn":"Pyro RES increased by 40%.","piece2DescVi":"Kháng nguyên tố Hỏa tăng 40%.","piece4DescEn":"Increases DMG against opponents affected by Pyro by 35%.","piece4DescVi":"Tăng 35% sát thương tạo thành cho kẻ địch bị ảnh hưởng nguyên tố Hỏa.","iconUrl":"/assets/artifacts/UI_RelicIcon_14003_4.webp"},
  {"id":"14004","nameEn":"Maiden Beloved","nameVi":"Thiếu Nữ Đáng Yêu","rarityList":[4,5],"piece2DescEn":"Character Healing Effectiveness +15%","piece2DescVi":"Hiệu quả trị liệu nhân vật tạo ra tăng 15%.","piece4DescEn":"Using an Elemental Skill or Burst increases healing received by all party members by 20% for 10s.","piece4DescVi":"10s sau khi thi triển kỹ năng Nguyên Tố hoặc Kỹ Năng Nộ, hiệu quả trị liệu tất cả nhân vật trong đội nhận được tăng 20%.","iconUrl":"/assets/artifacts/UI_RelicIcon_14004_4.webp"},
  {"id":"15001","nameEn":"Gladiator's Finale","nameVi":"Lễ Bế Mạc Của Giác Đấu Sĩ","rarityList":[4,5],"piece2DescEn":"ATK +18%.","piece2DescVi":"Tấn công tăng 18%","piece4DescEn":"If the wielder of this artifact set uses a Sword, Claymore or Polearm, increases their Normal Attack DMG by 35%.","piece4DescVi":"Khi nhân vật trang bị bộ Thánh Di Vật này dùng kiếm đơn, trọng kiếm, vũ khí cán dài, sát thương tấn công thường nhân vật tạo thành tăng 35%.","iconUrl":"/assets/artifacts/UI_RelicIcon_15001_4.webp"},
  {"id":"15002","nameEn":"Viridescent Venerer","nameVi":"Bóng Hình Màu Xanh","rarityList":[4,5],"piece2DescEn":"Anemo DMG Bonus +15%","piece2DescVi":"Nhận 15% buff sát thương nguyên tố Phong.","piece4DescEn":"Increases Swirl DMG by 60%. Decreases opponent's Elemental RES to the element infused in the Swirl by 40% for 10s.","piece4DescVi":"Sát thương phản ứng khuếch tán tạo thành tăng 60%. Dựa theo loại Nguyên Tố khuếch tán, giảm 40% kháng Nguyên Tố của kẻ địch bị ảnh hưởng, kéo dài 10s.","iconUrl":"/assets/artifacts/UI_RelicIcon_15002_4.webp"},
  {"id":"15003","nameEn":"Wanderer's Troupe","nameVi":"Đoàn Hát Lang Thang Đại Lục","rarityList":[4,5],"piece2DescEn":"Increases Elemental Mastery by 80.","piece2DescVi":"Tăng 80 điểm tinh thông nguyên tố.","piece4DescEn":"Increases Charged Attack DMG by 35% if the character uses a Catalyst or a Bow.","piece4DescVi":"Khi nhân vật trang bị bộ Thánh Di Vật này dùng pháp khí, cung tên, sát thương trọng kích nhân vật tạo thành tăng 35%.","iconUrl":"/assets/artifacts/UI_RelicIcon_15003_4.webp"},
  {"id":"15005","nameEn":"Thundering Fury","nameVi":"Như Sấm Thịnh Nộ","rarityList":[4,5],"piece2DescEn":"Electro DMG Bonus +15%","piece2DescVi":"Nhận 15% buff sát thương nguyên tố Lôi","piece4DescEn":"Increases the DMG caused by Overloaded, Electro-Charged, Superconduct, and Hyperbloom by 40%, the DMG Bonus conferred by Aggravate by 20%, and the DMG caused by Lunar-Charged by 20%. When Quicken or the aforementioned Elemental Reactions are triggered, Elemental Skill CD is decreased by 1s. Can only occur once every 0.8s.","piece4DescVi":"Sát thương tạo thành từ phản ứng Quá Tải, Điện Cảm, Siêu Dẫn, Nở Rộ tăng 40%; sát thương từ phản ứng Tăng Cường tăng 20%; sát thương từ phản ứng Nguyệt-Điện Cảm tăng 20%. Khi kích hoạt phản ứng Sinh Trưởng hoặc những phản ứng nêu trên, CD Kỹ Năng Nguyên Tố giảm 1s. Hiệu quả này mỗi 0.8s tối đa kích hoạt một lần.","iconUrl":"/assets/artifacts/UI_RelicIcon_15005_4.webp"}
];
