const fs = require('fs');
const path = require('path');
const https = require('https');

const EN_URL = 'https://gi.yatta.moe/api/v2/en/gcg';
const VI_URL = 'https://gi.yatta.moe/api/v2/vi/gcg';
const IMG_BASE_URL = 'https://gi.yatta.moe/assets/UI/gcg/';
const OUTPUT_JSON_FILE = path.join(__dirname, '../frontend/data/tcgCards.ts');
const IMG_OUTPUT_DIR = path.join(__dirname, '../frontend/public/images/tcg');

if (!fs.existsSync(IMG_OUTPUT_DIR)) {
  fs.mkdirSync(IMG_OUTPUT_DIR, { recursive: true });
}

// Helper to fetch JSON
const fetchJson = (url) => {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'GenshinHub/1.0' } }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
};

// Helper to download image
const downloadImage = (filename, url) => {
  return new Promise((resolve, reject) => {
    const dest = path.join(IMG_OUTPUT_DIR, filename);
    if (fs.existsSync(dest)) {
      return resolve(false); // Already exists
    }
    
    https.get(url, { headers: { 'User-Agent': 'GenshinHub/1.0' } }, (res) => {
      if (res.statusCode !== 200) {
        // Some cards might not have images yet or wrong URL
        console.warn(`Failed to download ${url} - Status ${res.statusCode}`);
        return resolve(false);
      }
      const file = fs.createWriteStream(dest);
      res.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve(true); // Downloaded
      });
    }).on('error', (err) => {
      fs.unlink(dest, () => {});
      reject(err);
    });
  });
};

// Concurrency helper
const chunkArray = (array, size) => {
  const chunks = [];
  for (let i = 0; i < array.length; i += size) chunks.push(array.slice(i, i + size));
  return chunks;
};

async function main() {
  console.log('Fetching EN TCG data...');
  const enRes = await fetchJson(EN_URL);
  
  console.log('Fetching VI TCG data...');
  const viRes = await fetchJson(VI_URL);

  const enData = enRes.data;
  const viData = viRes.data;

  console.log('enData keys length:', Object.keys(enData).length);
  const items = enData.items;
  const viItems = viData.items || {};

  console.log('Valid card keys:', Object.keys(items).length);

  const cardsList = [];
  const downloadsToRun = [];

  for (const [id, enCard] of Object.entries(items)) {
    const viCard = viItems[id] || {};
    
    cardsList.push({
      id: String(id),
      nameEn: enCard.name,
      nameVi: viCard.name || enCard.name,
      type: enCard.type,
      tags: Array.isArray(enCard.tags) ? enCard.tags : Object.values(enCard.tags || {}),
      icon: enCard.icon,
      route: enCard.route
    });

    if (enCard.icon) {
      downloadsToRun.push({
        filename: `${enCard.icon}.png`,
        url: `${IMG_BASE_URL}${enCard.icon}.png`
      });
    }
  }

  console.log(`Found ${cardsList.length} cards. Saving JSON...`);
  
  // Sort cards by ID
  cardsList.sort((a, b) => Number(a.id) - Number(b.id));

  const tsContent = `// Automatically generated by scratch/fetch_tcg.js\n\nexport interface TCGCard {\n  id: string;\n  nameEn: string;\n  nameVi: string;\n  type: string;\n  tags: string[];\n  icon: string;\n  route: string;\n}\n\nexport const tcgCards: TCGCard[] = ${JSON.stringify(cardsList, null, 2)};\n`;
  fs.writeFileSync(OUTPUT_JSON_FILE, tsContent, 'utf-8');

  console.log(`Starting image downloads (${downloadsToRun.length} images)...`);
  let downloadedCount = 0;
  
  // Download in chunks of 20 to avoid overwhelming network
  const batches = chunkArray(downloadsToRun, 20);
  for (let i = 0; i < batches.length; i++) {
    const batch = batches[i];
    const results = await Promise.all(batch.map(d => downloadImage(d.filename, d.url)));
    downloadedCount += results.filter(r => r).length;
    process.stdout.write(`\rProgress: Batch ${i + 1}/${batches.length} - Downloaded new images: ${downloadedCount}`);
  }
  
  console.log('\nDone! TCG Data and Images are ready.');
}

main().catch(console.error);
