  const charactersData = [
    ...[
      "Kamisato Ayaka|Cryo|Sword|5",
      "Jean|Anemo|Sword|5",
      "Lisa|Electro|Catalyst|4",
      "Barbara|Hydro|Catalyst|4",
      "Kaeya|Cryo|Sword|4",
      "Diluc|Pyro|Claymore|5",
      "Razor|Electro|Claymore|4",
      "Amber|Pyro|Bow|4",
      "Venti|Anemo|Bow|5",
      "Xiangling|Pyro|Catalyst|4",
      "Beidou|Electro|Claymore|4",
      "Xingqiu|Hydro|Sword|4",
      "Xiao|Anemo|Catalyst|5",
      "Ningguang|Geo|Catalyst|4",
      "Klee|Pyro|Catalyst|5",
      "Zhongli|Geo|Catalyst|5",
      "Fischl|Electro|Bow|4",
      "Bennett|Pyro|Sword|4",
      "Tartaglia|Hydro|Bow|5",
      "Noelle|Geo|Claymore|4",
      "Qiqi|Cryo|Sword|5",
      "Chongyun|Cryo|Claymore|4",
      "Ganyu|Cryo|Bow|5",
      "Albedo|Geo|Sword|5",
      "Diona|Cryo|Bow|4",
      "Mona|Hydro|Catalyst|5",
      "Keqing|Electro|Sword|5",
      "Sucrose|Anemo|Catalyst|4",
      "Xinyan|Pyro|Claymore|4",
      "Rosaria|Cryo|Catalyst|4",
      "Hu Tao|Pyro|Catalyst|5",
      "Kaedehara Kazuha|Anemo|Sword|5",
      "Yanfei|Pyro|Catalyst|4",
      "Yoimiya|Pyro|Bow|5",
      "Thoma|Pyro|Catalyst|4",
      "Eula|Cryo|Claymore|5",
      "Raiden Shogun|Electro|Catalyst|5",
      "Sayu|Anemo|Claymore|4",
      "Sangonomiya Kokomi|Hydro|Catalyst|5",
      "Gorou|Geo|Bow|4",
      "Kujou Sara|Electro|Bow|4",
      "Arataki Itto|Geo|Claymore|5",
      "Yae Miko|Electro|Catalyst|5",
      "Shikanoin Heizou|Anemo|Catalyst|4",
      "Yelan|Hydro|Bow|5",
      "Kirara|Dendro|Sword|4",
      "Aloy|Cryo|Bow|5",
      "Shenhe|Cryo|Catalyst|5",
      "Yun Jin|Geo|Catalyst|4",
      "Kuki Shinobu|Electro|Sword|4",
      "Kamisato Ayato|Hydro|Sword|5",
      "Collei|Dendro|Bow|4",
      "Dori|Electro|Claymore|4",
      "Tighnari|Dendro|Bow|5",
      "Nilou|Hydro|Sword|5",
      "Cyno|Electro|Catalyst|5",
      "Candace|Hydro|Catalyst|4",
      "Nahida|Dendro|Catalyst|5",
      "Layla|Cryo|Sword|4",
      "Wanderer|Anemo|Catalyst|5",
      "Faruzan|Anemo|Bow|4",
      "Yaoyao|Dendro|Catalyst|4",
      "Alhaitham|Dendro|Sword|5",
      "Dehya|Pyro|Claymore|5",
      "Mika|Cryo|Catalyst|4",
      "Kaveh|Dendro|Claymore|4",
      "Baizhu|Dendro|Catalyst|5",
      "Lynette|Anemo|Sword|4",
      "Lyney|Pyro|Bow|5",
      "Freminet|Cryo|Claymore|4",
      "Wriothesley|Cryo|Catalyst|5",
      "Neuvillette|Hydro|Catalyst|5",
      "Charlotte|Cryo|Catalyst|4",
      "Furina|Hydro|Sword|5",
      "Chevreuse|Pyro|Catalyst|4",
      "Navia|Geo|Claymore|5",
      "Gaming|Pyro|Claymore|4",
      "Xianyun|Anemo|Catalyst|5",
      "Chiori|Geo|Sword|5",
      "Sigewinne|Hydro|Bow|5",
      "Arlecchino|Pyro|Catalyst|5",
      "Sethos|Electro|Bow|4",
      "Clorinde|Electro|Sword|5",
      "Emilie|Dendro|Catalyst|5",
      "Kachina|Geo|Catalyst|4",
      "Kinich|Dendro|Claymore|5",
      "Mualani|Hydro|Catalyst|5",
      "Xilonen|Geo|Sword|5",
      "Chasca|Anemo|Bow|5",
      "Ororon|Electro|Bow|4",
      "Mavuika|Pyro|Claymore|5",
      "Citlali|Cryo|Catalyst|5",
      "Lan Yan|Anemo|Catalyst|4",
      "Yumemizuki Mizuki|Anemo|Catalyst|5",
      "Iansan|Electro|Catalyst|4",
      "Varesa|Electro|Catalyst|5",
      "Escoffier|Cryo|Catalyst|5",
      "Ifa|Anemo|Catalyst|4",
      "Skirk|Cryo|Sword|5",
      "Dahlia|Hydro|Sword|4",
      "Ineffa|Electro|Catalyst|5",
      "Manekin|None|Sword|5",
      "Manekina|None|Sword|5",
      "Lauma|Dendro|Catalyst|5",
      "Flins|Electro|Catalyst|5",
      "Aino|Hydro|Claymore|4",
      "Nefer|Dendro|Catalyst|5",
      "Durin|Pyro|Sword|5",
      "Jahoda|Anemo|Bow|4",
      "Columbina|Hydro|Catalyst|5",
      "Zibai|Geo|Sword|5",
      "Illuga|Geo|Catalyst|4",
      "Varka|Anemo|Claymore|5",
      "Lohen|Cryo|Catalyst|5",
      "Linnea|Geo|Bow|5",
      "Nicole|Pyro|Catalyst|5",
      "Prune|Anemo|Catalyst|4",
      "Traveler (Anemo)|Anemo|Sword|5",
      "Traveler (Geo)|Geo|Sword|5",
      "Traveler (Electro)|Electro|Sword|5",
      "Traveler (Dendro)|Dendro|Sword|5",
      "Traveler (Hydro)|Hydro|Sword|5",
      "Traveler (Pyro)|Pyro|Sword|5"
    ].map(c => ({ ...parseChar(c), region: "Other" }))
  ];